Rails.application.routes.draw do
  root to: 'components#all'
  get 'components/alert'
  get 'components/badge'
  get 'components/button'
  get 'components/buttongroup'
  get 'components/card'
  get 'components/carousel'
  get 'components/collapse'
  get 'components/dropdown'
  get 'components/form'
  get 'components/inputgroup'
  get 'components/jumbotron'
  get 'components/listgroup'
  get 'components/modal'
  get 'components/nav'
  get 'components/navbar'
  get 'components/popover'
  get 'components/scrollspy'
  get 'components/spinner'
  get 'components/toast'
  get 'components/tooltip'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
